name: Update README

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.email "elouahab.abdelaziz@gmail.com"
          git config --global user.name "MrAbdelaziz"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Run shell script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: bash update_readme.sh
