name: Update README

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Run shell script
        run: bash update_readme.sh
